# Generated by Django 3.0.7 on 2022-03-17 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorite_authors',
            field=models.ManyToManyField(blank=True, related_name='favorite_authors', to='library.Author'),
        ),
        migrations.AddField(
            model_name='user',
            name='favorite_books',
            field=models.ManyToManyField(blank=True, related_name='favorite_books', to='library.Book'),
        ),
        migrations.AddField(
            model_name='user',
            name='favorite_genres',
            field=models.ManyToManyField(blank=True, related_name='favorite_genres', to='library.Genre'),
        ),
    ]
